# This is the main configuration file of your Dancer app
# env-related settings should go to environments/$env.yml
# all the settings in this file will be loaded at Dancer's startup.

# Your application's name
appname: "Caretaker"

# The default layout to use for your application (located in
# views/layouts/main.tt)
layout: "before_login"

# when the charset is set to UTF-8 Dancer will handle for you
# all the magic of encoding and decoding. You should not care
# about unicode within your app when this setting is set (recommended).
charset: "UTF-8"

# template engine
# simple: default and very basic template engine
# template_toolkit: TT

#template: "simple"

template: "template_toolkit"
engines:
   template_toolkit:
     encoding:  'utf8'
     #start_tag: '[%'
     #end_tag:   '%]'

# Simple session handling
session: Simple

plugins:
    Database:
        driver: 'Pg'
        database: 'caretaker'
        host: 'localhost'
        port: 5432
        username: 'priyank'
        password: 'quidditch'
        dbi_params:
            RaiseError: 1
            AutoCommit: 1
        #on_connect_do: ["SET NAMES 'utf8'", "SET CHARACTER SET 'utf8'" ]
        #driver: 'SQLite'
        #database: 'starmaps_new.sqlite'
        log_queries: 1
log: 'core'

sites:
    linkedin:
        name: 'LinkedIn Authentication'
        client_id: 'wwrtgvlfym9u'
        client_secret: 'YJl9zMJsdOpy8GkB'
        site: 'https://api.linkedin.com'
        authorize_path: '/uas/oauth/authenticate'
        request_token_path: '/uas/oauth/requestToken'
        access_token_path: '/uas/oauth/accessToken'
        #scope: 'https://www.googleapis.com/auth/userinfo.email'
        #protected_resource_url: 'https://www.googleapis.com/oauth2/v2/userinfo'

